//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular_Save_ngroute.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public decimal sno { get; set; }
        public string sname { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<decimal> m1 { get; set; }
        public Nullable<decimal> m2 { get; set; }
        public Nullable<decimal> m3 { get; set; }
    }
}
